### PR TITLE
Updates to be able to create a dmg on MacOSX

### PR DESCRIPTION
**Pull request by thibauthourlier**
For these changes to work, it needs changes to be merged from https://github.com/thibauthourlier/ensembl-otter branch feature/mac_dmg into https://github.com/Ensembl/ensembl-otter branch master
It also needs a PR to be accepted for Zircon. This change is not required but could solve some problems

### CODE REVIEW

**Comment by mira13** [comment]
Why so much file and commits, impossible to review. Probably request is against wrong branch.

**Review by mira13 — CHANGES_REQUESTED** [review]
Needs explanation why so many file and commits

**Comment by thibauthourlier** [comment]
I cloned the Sanger repository few years ago when anacode still existed. Because this repository is a reload of the Sanger repository I do not have the same hashes.
Before doing the pull request I checked the last commit message on master and the last commit itself but I didn't check the hash of this commit. The two branches are the same but the hashes are different, this is why github wants to merge too many files and commits.

Is there a way to only use my commits in the pull request?

**Comment by mira13** [comment]
Probably the best way - to create a new branch and cherry-pick your commits.

**Comment by thibauthourlier** [comment]
I have the changes in a different branch, it was less painfull than expected. I will just do a run of the script to check that everything has been added correctly and I will resubmit a pull request hopefully tomorrow

**Pull request closed without merging**
